function clear(obj)
obj.dp_matrix=-1*ones(obj.N_cell_x, obj.N_cell_y, ...
                4, obj.time_slot_max+1);
obj.last_step_matrix=-1*ones(obj.N_cell_x, obj.N_cell_y,...
    4, obj.time_slot_max+1,4);
obj.visited_cells_matrix=zeros(obj.N_cell_x, obj.N_cell_y, ...
    4, obj.time_slot_max+1, obj.N_cell_x*obj.N_cell_y);
obj.visited_cells_matrix_2=zeros(obj.N_cell_x, obj.N_cell_y, ...
    4, obj.time_slot_max+1, obj.N_cell_x*obj.N_cell_y);
end